# Generated by Django 2.2 on 2020-03-29 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200328_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 3, 29, 7, 32, 0, 461766)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='background.jpeg', null=True, upload_to='profile-pics'),
        ),
    ]
