# Generated by Django 2.2 on 2020-03-28 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 7, 2, 39, 827784, tzinfo=utc))),
            ],
        ),
    ]
