# Generated by Django 2.2 on 2020-03-28 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 28, 7, 2, 45, 29450, tzinfo=utc)),
        ),
    ]
