# Generated by Django 2.2 on 2020-03-29 01:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200328_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 29, 1, 47, 0, 469882, tzinfo=utc)),
        ),
    ]
